package com.cheradip.ailanguagetutor.core.pack

/** Offline rich lexicon shipped with the app (English + Bengali only). */
object RichBundledLexicon {
    const val PACK_VERSION = 2
    val BUNDLED_LANGUAGE_CODES = setOf("en", "bn")

    fun samplePack(languageCode: String): SamplePackFile? = when (languageCode.lowercase()) {
        "en" -> SamplePackFile(
            version = PACK_VERSION,
            languageCode = "en",
            entries = englishEntries(),
            phrases = mapOf(
                "good morning" to "A polite greeting used in the morning.",
                "thank you" to "Expression of gratitude.",
                "how are you" to "A common greeting asking about someone's state.",
                "good night" to "A polite farewell at night.",
                "see you" to "Informal goodbye.",
            ),
            translations = mapOf(
                "hello|fr" to "bonjour",
                "thank you|fr" to "merci",
                "hello|es" to "hola",
                "thank you|es" to "gracias",
                "hello|bn" to "নমস্কার",
                "thank you|bn" to "ধন্যবাদ",
                "father|bn" to "পিতা",
                "mother|bn" to "মাতা",
                "parents|bn" to "পিতা-মাতা",
                "about|bn" to "সম্পর্কে",
                "essay|bn" to "রচনা",
                "word|bn" to "শব্দ",
                "words|bn" to "শব্দ",
                "within|bn" to "মধ্যে",
                "me|bn" to "আমাকে",
                "give|bn" to "দাও",
                "write|bn" to "লিখতে",
                "I|bn" to "আমি",
            ),
        )
        "bn" -> SamplePackFile(
            version = PACK_VERSION,
            languageCode = "bn",
            entries = bengaliEntries(),
            phrases = mapOf(
                "আপনি কেমন আছেন" to "How are you? (formal)",
                "অনেক ধন্যবাদ" to "Thank you very much.",
                "শুভ সকাল" to "Good morning.",
            ),
            translations = mapOf(
                "নমস্কার|en" to "hello",
                "ধন্যবাদ|en" to "thank you",
                "বই|en" to "book",
                "পিতা|en" to "father",
                "মাতা|en" to "mother",
                "পিতা-মাতা|en" to "parents",
                "সম্পর্কে|en" to "about",
                "রচনা|en" to "essay",
                "শব্দ|en" to "word",
                "শব্দের|en" to "word",
                "মধ্যে|en" to "within",
                "আমাকে|en" to "me",
                "একটি|en" to "a",
                "লিখে|en" to "write",
                "লিখতে|en" to "write",
                "আমি|en" to "I",
                "দাও|en" to "give",
            ),
        )
        else -> null
    }

    private fun englishEntries(): Map<String, List<String>> = mapOf(
        // Core tutor vocabulary
        "hello" to listOf("a greeting", "used to attract attention"),
        "world" to listOf("the earth", "human society"),
        "learn" to listOf("gain knowledge", "memorize"),
        "learning" to listOf("the process of gaining knowledge"),
        "language" to listOf("system of communication", "speech of a nation"),
        "book" to listOf("written work", "bound pages"),
        "read" to listOf("look at and comprehend text", "interpret symbols"),
        "reading" to listOf("the action of looking at and understanding text"),
        "word" to listOf("single unit of language", "promise"),
        "words" to listOf("units of language", "vocabulary"),
        "sentence" to listOf("a set of words expressing a complete thought"),
        "paragraph" to listOf("a section of writing", "a distinct part of a text"),
        "good" to listOf("of high quality", "morally right"),
        "morning" to listOf("early part of the day"),
        "thank" to listOf("express gratitude"),
        "thanks" to listOf("expression of gratitude"),
        "you" to listOf("second person pronoun"),
        "yes" to listOf("affirmative response"),
        "no" to listOf("negative response"),
        "water" to listOf("clear liquid essential for life"),
        "food" to listOf("substance eaten for nourishment"),
        "friend" to listOf("person you know and like"),
        "family" to listOf("group of related people"),
        "school" to listOf("place of learning"),
        "teacher" to listOf("person who teaches"),
        "student" to listOf("person who studies"),
        "please" to listOf("polite request word"),
        "sorry" to listOf("expression of regret"),
        "name" to listOf("word by which someone is known"),
        "day" to listOf("24-hour period"),
        "night" to listOf("dark part of the day"),
        "time" to listOf("measurable duration"),
        "question" to listOf("sentence asking for information"),
        "answer" to listOf("response to a question"),
        "speak" to listOf("talk", "use voice"),
        "write" to listOf("form letters or words"),
        "listen" to listOf("pay attention to sound", "hear deliberately"),
        "scan" to listOf("look at carefully", "capture an image of text"),
        "document" to listOf("written or printed paper", "digital file with text"),
        "translate" to listOf("express in another language"),
        "translation" to listOf("rendering in another language"),
        "practice" to listOf("repeated exercise to improve skill"),
        "study" to listOf("learn about a subject", "review material"),
        "grammar" to listOf("rules of a language", "sentence structure"),
        "meaning" to listOf("what a word or phrase expresses"),
        "pronunciation" to listOf("way a word is spoken"),
        // High-frequency function words
        "the" to listOf("definite article"),
        "a" to listOf("indefinite article"),
        "an" to listOf("indefinite article before vowel sound"),
        "and" to listOf("conjunction connecting words or phrases"),
        "or" to listOf("alternative conjunction"),
        "but" to listOf("contrast conjunction"),
        "is" to listOf("third person singular of 'be'"),
        "are" to listOf("plural form of 'be'"),
        "was" to listOf("past singular of 'be'"),
        "were" to listOf("past plural of 'be'"),
        "be" to listOf("exist", "used as auxiliary verb"),
        "have" to listOf("possess", "auxiliary for perfect tenses"),
        "has" to listOf("third person singular of 'have'"),
        "had" to listOf("past of 'have'"),
        "do" to listOf("perform an action", "auxiliary verb"),
        "does" to listOf("third person singular of 'do'"),
        "did" to listOf("past of 'do'"),
        "will" to listOf("future auxiliary", "intention"),
        "would" to listOf("conditional form of 'will'"),
        "can" to listOf("be able to"),
        "could" to listOf("past of 'can'", "polite request"),
        "should" to listOf("ought to", "recommendation"),
        "may" to listOf("permission", "possibility"),
        "might" to listOf("possibility"),
        "must" to listOf("necessity", "obligation"),
        "in" to listOf("inside", "within"),
        "on" to listOf("upon", "about"),
        "at" to listOf("location or time point"),
        "to" to listOf("direction", "infinitive marker"),
        "for" to listOf("purpose", "benefit of"),
        "of" to listOf("belonging to", "made from"),
        "with" to listOf("accompanied by", "using"),
        "from" to listOf("starting point", "origin"),
        "by" to listOf("near", "through agent"),
        "about" to listOf("concerning", "approximately"),
        "this" to listOf("near demonstrative"),
        "that" to listOf("far demonstrative"),
        "these" to listOf("plural of 'this'"),
        "those" to listOf("plural of 'that'"),
        "i" to listOf("first person singular pronoun"),
        "we" to listOf("first person plural pronoun"),
        "he" to listOf("third person masculine pronoun"),
        "she" to listOf("third person feminine pronoun"),
        "it" to listOf("third person neuter pronoun"),
        "they" to listOf("third person plural pronoun"),
        "my" to listOf("belonging to me"),
        "your" to listOf("belonging to you"),
        "his" to listOf("belonging to him"),
        "her" to listOf("belonging to her", "object pronoun"),
        "our" to listOf("belonging to us"),
        "their" to listOf("belonging to them"),
        "what" to listOf("asking for information"),
        "when" to listOf("at what time"),
        "where" to listOf("at what place"),
        "why" to listOf("for what reason"),
        "how" to listOf("in what way"),
        "who" to listOf("what person"),
        "which" to listOf("what one of a set"),
        // Numbers as words
        "zero" to listOf("the number 0"),
        "one" to listOf("the number 1"),
        "two" to listOf("the number 2"),
        "three" to listOf("the number 3"),
        "four" to listOf("the number 4"),
        "five" to listOf("the number 5"),
        "six" to listOf("the number 6"),
        "seven" to listOf("the number 7"),
        "eight" to listOf("the number 8"),
        "nine" to listOf("the number 9"),
        "ten" to listOf("the number 10"),
    )

    private fun bengaliEntries(): Map<String, List<String>> = mapOf(
        "নমস্কার" to listOf("hello", "greeting"),
        "ধন্যবাদ" to listOf("thank you"),
        "বই" to listOf("book"),
        "শেখা" to listOf("to learn", "learning"),
        "শব্দ" to listOf("word"),
        "শব্দের" to listOf("word", "of word"),
        "পড়া" to listOf("to read", "reading"),
        "ভাষা" to listOf("language"),
        "সকাল" to listOf("morning"),
        "ভালো" to listOf("good", "well"),
        "বিশ্ব" to listOf("world"),
        "হ্যাঁ" to listOf("yes"),
        "না" to listOf("no"),
        "পানি" to listOf("water"),
        "খাবার" to listOf("food"),
        "বন্ধু" to listOf("friend"),
        "পরিবার" to listOf("family"),
        "স্কুল" to listOf("school"),
        "শিক্ষক" to listOf("teacher"),
        "ছাত্র" to listOf("student"),
        "দয়া করে" to listOf("please"),
        "দুঃখিত" to listOf("sorry"),
        "নাম" to listOf("name"),
        "দিন" to listOf("day"),
        "রাত" to listOf("night"),
        "সময়" to listOf("time"),
        "প্রশ্ন" to listOf("question"),
        "উত্তর" to listOf("answer"),
        "কথা বলা" to listOf("to speak"),
        "লেখা" to listOf("to write", "writing"),
        "শুভ সকাল" to listOf("good morning"),
        "আমি" to listOf("I"),
        "আপনি" to listOf("you (formal)"),
        "তুমি" to listOf("you (informal)"),
        "আমরা" to listOf("we"),
        "তারা" to listOf("they"),
        "এবং" to listOf("and"),
        "কিন্তু" to listOf("but"),
        "কি" to listOf("what"),
        "কেন" to listOf("why"),
        "কখন" to listOf("when"),
        "কোথায়" to listOf("where"),
        "কিভাবে" to listOf("how"),
        "পিতা" to listOf("father"),
        "মাতা" to listOf("mother"),
        "পিতা-মাতা" to listOf("parents"),
        "সম্পর্কে" to listOf("about"),
        "রচনা" to listOf("essay", "composition"),
        "মধ্যে" to listOf("within", "inside", "among"),
        "দাও" to listOf("give"),
        "আমাকে" to listOf("to me", "me"),
        "একটি" to listOf("a", "one"),
        "লিখে" to listOf("write", "by writing"),
        "লিখতে" to listOf("to write"),
        "২০০" to listOf("200"),
    )
}
