package com.cheradip.packbuilder

import com.cheradip.packbuilder.model.LanguagePackSeed
import com.cheradip.packbuilder.model.PhraseTranslation
import com.cheradip.packbuilder.model.QaPair
import com.cheradip.packbuilder.model.WordSeed
import com.cheradip.packbuilder.model.WordTranslation

/** Rich starter vocabulary for tier-1 launch languages (ported from build_language_packs.py). */
object Tier1PackData {
    private fun word(
        word: String,
        lang: String,
        meanings: List<String>,
        freq: Number = 900.0,
        lemma: String = word,
    ) = WordSeed(word, lemma, lang, freq.toDouble(), meanings)

    private fun enEntries(): List<WordSeed> = listOf(
        word("hello", "en", listOf("a greeting", "used to attract attention"), 9800),
        word("world", "en", listOf("the earth", "human society"), 9500),
        word("learn", "en", listOf("gain knowledge", "memorize"), 9200),
        word("language", "en", listOf("system of communication", "speech of a nation"), 9100),
        word("book", "en", listOf("written work", "bound pages"), 9000),
        word("read", "en", listOf("look at and comprehend text", "interpret symbols"), 8900),
        word("word", "en", listOf("single unit of language", "promise"), 8800),
        word("good", "en", listOf("of high quality", "morally right"), 8700),
        word("morning", "en", listOf("early part of the day"), 8600),
        word("thank", "en", listOf("express gratitude"), 8500),
        word("you", "en", listOf("second person pronoun"), 8400),
        word("yes", "en", listOf("affirmative response"), 8300),
        word("no", "en", listOf("negative response"), 8200),
        word("water", "en", listOf("clear liquid essential for life"), 8100),
        word("food", "en", listOf("substance eaten for nourishment"), 8000),
        word("friend", "en", listOf("person you know and like"), 7900),
        word("family", "en", listOf("group of related people"), 7800),
        word("school", "en", listOf("place of learning"), 7700),
        word("teacher", "en", listOf("person who teaches"), 7600),
        word("student", "en", listOf("person who studies"), 7500),
        word("please", "en", listOf("polite request word"), 7400),
        word("sorry", "en", listOf("expression of regret"), 7300),
        word("name", "en", listOf("word by which someone is known"), 7200),
        word("day", "en", listOf("24-hour period"), 7100),
        word("night", "en", listOf("dark part of the day"), 7000),
        word("time", "en", listOf("measurable duration"), 6900),
        word("question", "en", listOf("sentence asking for information"), 6800),
        word("answer", "en", listOf("response to a question"), 6700),
        word("speak", "en", listOf("talk, use voice"), 6600),
        word("write", "en", listOf("form letters or words"), 6500),
    )

    private val packs: Map<String, LanguagePackSeed> = mapOf(
        "en" to LanguagePackSeed(
            languageCode = "en",
            words = enEntries(),
            phrases = listOf(
                PhraseTranslation("good morning", "en", "en", "A polite greeting used in the morning."),
                PhraseTranslation("thank you", "en", "en", "Expression of gratitude."),
                PhraseTranslation("how are you", "en", "en", "A common greeting asking about someone's state."),
            ),
            wordTranslations = listOf(
                WordTranslation("hello", "en", "bonjour", "fr"),
                WordTranslation("hello", "en", "hola", "es"),
                WordTranslation("thank you", "en", "merci", "fr"),
                WordTranslation("thank you", "en", "gracias", "es"),
            ),
            qaPairs = listOf(
                QaPair("What does hello mean?", "en", "Hello is a common English greeting.", "en"),
            ),
        ),
        "fr" to LanguagePackSeed(
            languageCode = "fr",
            words = listOf(
                word("bonjour", "fr", listOf("hello", "good day"), 9800),
                word("merci", "fr", listOf("thank you"), 9700),
                word("français", "fr", listOf("French language", "French people"), 9600),
                word("livre", "fr", listOf("book"), 9500),
                word("apprendre", "fr", listOf("to learn"), 9400),
                word("mot", "fr", listOf("word"), 9300),
                word("lire", "fr", listOf("to read"), 9200),
                word("langue", "fr", listOf("language", "tongue"), 9100),
                word("matin", "fr", listOf("morning"), 9000),
                word("bien", "fr", listOf("good", "well"), 8900),
                word("oui", "fr", listOf("yes"), 8800),
                word("non", "fr", listOf("no"), 8700),
                word("eau", "fr", listOf("water"), 8600),
                word("nourriture", "fr", listOf("food"), 8500),
                word("ami", "fr", listOf("friend"), 8400),
                word("famille", "fr", listOf("family"), 8300),
                word("école", "fr", listOf("school"), 8200),
                word("professeur", "fr", listOf("teacher"), 8100),
                word("étudiant", "fr", listOf("student"), 8000),
                word("s'il vous plaît", "fr", listOf("please"), 7900),
                word("pardon", "fr", listOf("sorry", "excuse me"), 7800),
                word("nom", "fr", listOf("name"), 7700),
                word("jour", "fr", listOf("day"), 7600),
                word("nuit", "fr", listOf("night"), 7500),
                word("temps", "fr", listOf("time", "weather"), 7400),
                word("question", "fr", listOf("question"), 7300),
                word("réponse", "fr", listOf("answer"), 7200),
                word("parler", "fr", listOf("to speak"), 7100),
                word("écrire", "fr", listOf("to write"), 7000),
                word("monde", "fr", listOf("world"), 6900),
            ),
            phrases = listOf(
                PhraseTranslation("bonjour", "fr", "fr", "Standard French greeting."),
                PhraseTranslation("comment allez-vous", "fr", "fr", "Formal: how are you?"),
                PhraseTranslation("merci beaucoup", "fr", "fr", "Thank you very much."),
            ),
            wordTranslations = listOf(
                WordTranslation("bonjour", "fr", "hello", "en"),
                WordTranslation("merci", "fr", "thank you", "en"),
                WordTranslation("bonjour", "fr", "hola", "es"),
            ),
            qaPairs = listOf(
                QaPair("Que signifie bonjour?", "fr", "Bonjour signifie hello ou good morning.", "fr"),
            ),
        ),
        "es" to LanguagePackSeed(
            languageCode = "es",
            words = listOf(
                word("hola", "es", listOf("hello"), 9800),
                word("gracias", "es", listOf("thank you"), 9700),
                word("libro", "es", listOf("book"), 9600),
                word("aprender", "es", listOf("to learn"), 9500),
                word("palabra", "es", listOf("word"), 9400),
                word("leer", "es", listOf("to read"), 9300),
                word("idioma", "es", listOf("language"), 9200),
                word("mañana", "es", listOf("morning", "tomorrow"), 9100),
                word("bueno", "es", listOf("good"), 9000),
                word("mundo", "es", listOf("world"), 8900),
                word("sí", "es", listOf("yes"), 8800),
                word("no", "es", listOf("no"), 8700),
                word("agua", "es", listOf("water"), 8600),
                word("comida", "es", listOf("food"), 8500),
                word("amigo", "es", listOf("friend"), 8400),
                word("familia", "es", listOf("family"), 8300),
                word("escuela", "es", listOf("school"), 8200),
                word("profesor", "es", listOf("teacher"), 8100),
                word("estudiante", "es", listOf("student"), 8000),
                word("por favor", "es", listOf("please"), 7900),
                word("lo siento", "es", listOf("sorry"), 7800),
                word("nombre", "es", listOf("name"), 7700),
                word("día", "es", listOf("day"), 7600),
                word("noche", "es", listOf("night"), 7500),
                word("tiempo", "es", listOf("time", "weather"), 7400),
                word("pregunta", "es", listOf("question"), 7300),
                word("respuesta", "es", listOf("answer"), 7200),
                word("hablar", "es", listOf("to speak"), 7100),
                word("escribir", "es", listOf("to write"), 7000),
                word("lengua", "es", listOf("language", "tongue"), 6900),
            ),
            phrases = listOf(
                PhraseTranslation("buenos días", "es", "es", "Good morning."),
                PhraseTranslation("muchas gracias", "es", "es", "Thank you very much."),
                PhraseTranslation("¿cómo estás?", "es", "es", "How are you? (informal)"),
            ),
            wordTranslations = listOf(
                WordTranslation("hola", "es", "hello", "en"),
                WordTranslation("gracias", "es", "thank you", "en"),
                WordTranslation("hola", "es", "bonjour", "fr"),
            ),
        ),
        "de" to LanguagePackSeed(
            languageCode = "de",
            words = listOf(
                word("hallo", "de", listOf("hello"), 9800),
                word("danke", "de", listOf("thank you"), 9700),
                word("buch", "de", listOf("book"), 9600),
                word("lernen", "de", listOf("to learn"), 9500),
                word("wort", "de", listOf("word"), 9400),
                word("lesen", "de", listOf("to read"), 9300),
                word("sprache", "de", listOf("language"), 9200),
                word("morgen", "de", listOf("morning", "tomorrow"), 9100),
                word("gut", "de", listOf("good"), 9000),
                word("welt", "de", listOf("world"), 8900),
                word("ja", "de", listOf("yes"), 8800),
                word("nein", "de", listOf("no"), 8700),
                word("wasser", "de", listOf("water"), 8600),
                word("essen", "de", listOf("food", "to eat"), 8500),
                word("freund", "de", listOf("friend"), 8400),
                word("familie", "de", listOf("family"), 8300),
                word("schule", "de", listOf("school"), 8200),
                word("lehrer", "de", listOf("teacher"), 8100),
                word("schüler", "de", listOf("student"), 8000),
                word("bitte", "de", listOf("please"), 7900),
                word("entschuldigung", "de", listOf("sorry", "excuse me"), 7800),
                word("name", "de", listOf("name"), 7700),
                word("tag", "de", listOf("day"), 7600),
                word("nacht", "de", listOf("night"), 7500),
                word("zeit", "de", listOf("time"), 7400),
                word("frage", "de", listOf("question"), 7300),
                word("antwort", "de", listOf("answer"), 7200),
                word("sprechen", "de", listOf("to speak"), 7100),
                word("schreiben", "de", listOf("to write"), 7000),
                word("guten morgen", "de", listOf("good morning"), 6900),
            ),
            phrases = listOf(
                PhraseTranslation("guten morgen", "de", "de", "Good morning."),
                PhraseTranslation("vielen dank", "de", "de", "Thank you very much."),
                PhraseTranslation("wie geht es dir", "de", "de", "How are you?"),
            ),
            wordTranslations = listOf(
                WordTranslation("hallo", "de", "hello", "en"),
                WordTranslation("danke", "de", "thank you", "en"),
            ),
        ),
        "bn" to LanguagePackSeed(
            languageCode = "bn",
            words = listOf(
                word("নমস্কার", "bn", listOf("hello", "greeting"), 9800),
                word("ধন্যবাদ", "bn", listOf("thank you"), 9700),
                word("বই", "bn", listOf("book"), 9600),
                word("শেখা", "bn", listOf("to learn"), 9500),
                word("শব্দ", "bn", listOf("word"), 9400),
                word("পড়া", "bn", listOf("to read"), 9300),
                word("ভাষা", "bn", listOf("language"), 9200),
                word("সকাল", "bn", listOf("morning"), 9100),
                word("ভালো", "bn", listOf("good"), 9000),
                word("বিশ্ব", "bn", listOf("world"), 8900),
                word("হ্যাঁ", "bn", listOf("yes"), 8800),
                word("না", "bn", listOf("no"), 8700),
                word("পানি", "bn", listOf("water"), 8600),
                word("খাবার", "bn", listOf("food"), 8500),
                word("বন্ধু", "bn", listOf("friend"), 8400),
                word("পরিবার", "bn", listOf("family"), 8300),
                word("স্কুল", "bn", listOf("school"), 8200),
                word("শিক্ষক", "bn", listOf("teacher"), 8100),
                word("ছাত্র", "bn", listOf("student"), 8000),
                word("দয়া করে", "bn", listOf("please"), 7900),
                word("দুঃখিত", "bn", listOf("sorry"), 7800),
                word("নাম", "bn", listOf("name"), 7700),
                word("দিন", "bn", listOf("day"), 7600),
                word("রাত", "bn", listOf("night"), 7500),
                word("সময়", "bn", listOf("time"), 7400),
                word("প্রশ্ন", "bn", listOf("question"), 7300),
                word("উত্তর", "bn", listOf("answer"), 7200),
                word("কথা বলা", "bn", listOf("to speak"), 7100),
                word("লেখা", "bn", listOf("to write"), 7000),
                word("শুভ সকাল", "bn", listOf("good morning"), 6900),
            ),
            phrases = listOf(
                PhraseTranslation("আপনি কেমন আছেন", "bn", "bn", "How are you? (formal)"),
                PhraseTranslation("অনেক ধন্যবাদ", "bn", "bn", "Thank you very much."),
            ),
            wordTranslations = listOf(
                WordTranslation("নমস্কার", "bn", "hello", "en"),
                WordTranslation("ধন্যবাদ", "bn", "thank you", "en"),
            ),
        ),
        "hi" to LanguagePackSeed(
            languageCode = "hi",
            words = listOf(
                word("नमस्ते", "hi", listOf("hello", "greeting"), 9800),
                word("धन्यवाद", "hi", listOf("thank you"), 9700),
                word("किताब", "hi", listOf("book"), 9600),
                word("सीखना", "hi", listOf("to learn"), 9500),
                word("शब्द", "hi", listOf("word"), 9400),
                word("पढ़ना", "hi", listOf("to read"), 9300),
                word("भाषा", "hi", listOf("language"), 9200),
                word("सुप्रभात", "hi", listOf("good morning"), 9100),
                word("अच्छा", "hi", listOf("good"), 9000),
                word("दुनिया", "hi", listOf("world"), 8900),
                word("हाँ", "hi", listOf("yes"), 8800),
                word("नहीं", "hi", listOf("no"), 8700),
                word("पानी", "hi", listOf("water"), 8600),
                word("खाना", "hi", listOf("food"), 8500),
                word("दोस्त", "hi", listOf("friend"), 8400),
                word("परिवार", "hi", listOf("family"), 8300),
                word("स्कूल", "hi", listOf("school"), 8200),
                word("शिक्षक", "hi", listOf("teacher"), 8100),
                word("छात्र", "hi", listOf("student"), 8000),
                word("कृपया", "hi", listOf("please"), 7900),
                word("माफ़ कीजिए", "hi", listOf("sorry"), 7800),
                word("नाम", "hi", listOf("name"), 7700),
                word("दिन", "hi", listOf("day"), 7600),
                word("रात", "hi", listOf("night"), 7500),
                word("समय", "hi", listOf("time"), 7400),
                word("प्रश्न", "hi", listOf("question"), 7300),
                word("उत्तर", "hi", listOf("answer"), 7200),
                word("बोलना", "hi", listOf("to speak"), 7100),
                word("लिखना", "hi", listOf("to write"), 7000),
                word("पढ़ाई", "hi", listOf("study"), 6900),
            ),
            phrases = listOf(
                PhraseTranslation("आप कैसे हैं", "hi", "hi", "How are you? (formal)"),
                PhraseTranslation("बहुत धन्यवाद", "hi", "hi", "Thank you very much."),
            ),
            wordTranslations = listOf(
                WordTranslation("नमस्ते", "hi", "hello", "en"),
                WordTranslation("धन्यवाद", "hi", "thank you", "en"),
            ),
        ),
        "ar" to LanguagePackSeed(
            languageCode = "ar",
            words = listOf(
                word("مرحبا", "ar", listOf("hello"), 9800),
                word("شكرا", "ar", listOf("thank you"), 9700),
                word("كتاب", "ar", listOf("book"), 9600),
                word("تعلم", "ar", listOf("to learn"), 9500),
                word("كلمة", "ar", listOf("word"), 9400),
                word("قراءة", "ar", listOf("reading"), 9300),
                word("لغة", "ar", listOf("language"), 9200),
                word("صباح", "ar", listOf("morning"), 9100),
                word("جيد", "ar", listOf("good"), 9000),
                word("عالم", "ar", listOf("world"), 8900),
                word("نعم", "ar", listOf("yes"), 8800),
                word("لا", "ar", listOf("no"), 8700),
                word("ماء", "ar", listOf("water"), 8600),
                word("طعام", "ar", listOf("food"), 8500),
                word("صديق", "ar", listOf("friend"), 8400),
                word("عائلة", "ar", listOf("family"), 8300),
                word("مدرسة", "ar", listOf("school"), 8200),
                word("معلم", "ar", listOf("teacher"), 8100),
                word("طالب", "ar", listOf("student"), 8000),
                word("من فضلك", "ar", listOf("please"), 7900),
                word("آسف", "ar", listOf("sorry"), 7800),
                word("اسم", "ar", listOf("name"), 7700),
                word("يوم", "ar", listOf("day"), 7600),
                word("ليل", "ar", listOf("night"), 7500),
                word("وقت", "ar", listOf("time"), 7400),
                word("سؤال", "ar", listOf("question"), 7300),
                word("جواب", "ar", listOf("answer"), 7200),
                word("تحدث", "ar", listOf("to speak"), 7100),
                word("اكتب", "ar", listOf("to write"), 7000),
                word("صباح الخير", "ar", listOf("good morning"), 6900),
            ),
            phrases = listOf(
                PhraseTranslation("صباح الخير", "ar", "ar", "Good morning."),
                PhraseTranslation("شكرا جزيلا", "ar", "ar", "Thank you very much."),
            ),
            wordTranslations = listOf(
                WordTranslation("مرحبا", "ar", "hello", "en"),
                WordTranslation("شكرا", "ar", "thank you", "en"),
            ),
        ),
        "ja" to LanguagePackSeed(
            languageCode = "ja",
            words = listOf(
                word("こんにちは", "ja", listOf("hello", "good afternoon"), 9800),
                word("ありがとう", "ja", listOf("thank you"), 9700),
                word("本", "ja", listOf("book"), 9600),
                word("学ぶ", "ja", listOf("to learn"), 9500),
                word("言葉", "ja", listOf("word", "language"), 9400),
                word("読む", "ja", listOf("to read"), 9300),
                word("言語", "ja", listOf("language"), 9200),
                word("おはよう", "ja", listOf("good morning"), 9100),
                word("良い", "ja", listOf("good"), 9000),
                word("世界", "ja", listOf("world"), 8900),
                word("はい", "ja", listOf("yes"), 8800),
                word("いいえ", "ja", listOf("no"), 8700),
                word("水", "ja", listOf("water"), 8600),
                word("食べ物", "ja", listOf("food"), 8500),
                word("友達", "ja", listOf("friend"), 8400),
                word("家族", "ja", listOf("family"), 8300),
                word("学校", "ja", listOf("school"), 8200),
                word("先生", "ja", listOf("teacher"), 8100),
                word("学生", "ja", listOf("student"), 8000),
                word("お願い", "ja", listOf("please"), 7900),
                word("ごめん", "ja", listOf("sorry"), 7800),
                word("名前", "ja", listOf("name"), 7700),
                word("日", "ja", listOf("day"), 7600),
                word("夜", "ja", listOf("night"), 7500),
                word("時間", "ja", listOf("time"), 7400),
                word("質問", "ja", listOf("question"), 7300),
                word("答え", "ja", listOf("answer"), 7200),
                word("話す", "ja", listOf("to speak"), 7100),
                word("書く", "ja", listOf("to write"), 7000),
                word("勉強", "ja", listOf("study"), 6900),
            ),
            phrases = listOf(
                PhraseTranslation("おはようございます", "ja", "ja", "Good morning (polite)."),
                PhraseTranslation("ありがとうございます", "ja", "ja", "Thank you (polite)."),
            ),
            wordTranslations = listOf(
                WordTranslation("こんにちは", "ja", "hello", "en"),
                WordTranslation("ありがとう", "ja", "thank you", "en"),
            ),
        ),
        "pt" to LanguagePackSeed(
            languageCode = "pt",
            words = listOf(
                word("olá", "pt", listOf("hello"), 9800),
                word("obrigado", "pt", listOf("thank you (m)"), 9700),
                word("obrigada", "pt", listOf("thank you (f)"), 9650),
                word("livro", "pt", listOf("book"), 9600),
                word("aprender", "pt", listOf("to learn"), 9500),
                word("palavra", "pt", listOf("word"), 9400),
                word("ler", "pt", listOf("to read"), 9300),
                word("língua", "pt", listOf("language"), 9200),
                word("manhã", "pt", listOf("morning"), 9100),
                word("bom", "pt", listOf("good"), 9000),
                word("mundo", "pt", listOf("world"), 8900),
                word("sim", "pt", listOf("yes"), 8800),
                word("não", "pt", listOf("no"), 8700),
                word("água", "pt", listOf("water"), 8600),
                word("comida", "pt", listOf("food"), 8500),
                word("amigo", "pt", listOf("friend"), 8400),
                word("família", "pt", listOf("family"), 8300),
                word("escola", "pt", listOf("school"), 8200),
                word("professor", "pt", listOf("teacher"), 8100),
                word("estudante", "pt", listOf("student"), 8000),
                word("por favor", "pt", listOf("please"), 7900),
                word("desculpe", "pt", listOf("sorry"), 7800),
                word("nome", "pt", listOf("name"), 7700),
                word("dia", "pt", listOf("day"), 7600),
                word("noite", "pt", listOf("night"), 7500),
                word("tempo", "pt", listOf("time", "weather"), 7400),
                word("pergunta", "pt", listOf("question"), 7300),
                word("resposta", "pt", listOf("answer"), 7200),
                word("falar", "pt", listOf("to speak"), 7100),
                word("escrever", "pt", listOf("to write"), 7000),
            ),
            phrases = listOf(
                PhraseTranslation("bom dia", "pt", "pt", "Good morning."),
                PhraseTranslation("muito obrigado", "pt", "pt", "Thank you very much."),
            ),
            wordTranslations = listOf(
                WordTranslation("olá", "pt", "hello", "en"),
                WordTranslation("obrigado", "pt", "thank you", "en"),
            ),
        ),
        "zh" to LanguagePackSeed(
            languageCode = "zh",
            words = listOf(
                word("你好", "zh", listOf("hello"), 9800),
                word("谢谢", "zh", listOf("thank you"), 9700),
                word("书", "zh", listOf("book"), 9600),
                word("学习", "zh", listOf("to learn", "study"), 9500),
                word("词", "zh", listOf("word"), 9400),
                word("读", "zh", listOf("to read"), 9300),
                word("语言", "zh", listOf("language"), 9200),
                word("早上", "zh", listOf("morning"), 9100),
                word("好", "zh", listOf("good"), 9000),
                word("世界", "zh", listOf("world"), 8900),
                word("是", "zh", listOf("yes"), 8800),
                word("不", "zh", listOf("no", "not"), 8700),
                word("水", "zh", listOf("water"), 8600),
                word("食物", "zh", listOf("food"), 8500),
                word("朋友", "zh", listOf("friend"), 8400),
                word("家庭", "zh", listOf("family"), 8300),
                word("学校", "zh", listOf("school"), 8200),
                word("老师", "zh", listOf("teacher"), 8100),
                word("学生", "zh", listOf("student"), 8000),
                word("请", "zh", listOf("please"), 7900),
                word("对不起", "zh", listOf("sorry"), 7800),
                word("名字", "zh", listOf("name"), 7700),
                word("天", "zh", listOf("day"), 7600),
                word("晚上", "zh", listOf("night"), 7500),
                word("时间", "zh", listOf("time"), 7400),
                word("问题", "zh", listOf("question"), 7300),
                word("答案", "zh", listOf("answer"), 7200),
                word("说", "zh", listOf("to speak"), 7100),
                word("写", "zh", listOf("to write"), 7000),
                word("早上好", "zh", listOf("good morning"), 6900),
            ),
            phrases = listOf(
                PhraseTranslation("早上好", "zh", "zh", "Good morning."),
                PhraseTranslation("非常感谢", "zh", "zh", "Thank you very much."),
            ),
            wordTranslations = listOf(
                WordTranslation("你好", "zh", "hello", "en"),
                WordTranslation("谢谢", "zh", "thank you", "en"),
            ),
        ),
    )

    fun get(code: String): LanguagePackSeed? = packs[code.lowercase()]
}
